### ISSUE TITLE
Moving element without saving produces artifacts

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#117]
Repro:

Use latest WATT
Create Sample Web App project (TAU Based)
Open DE
Drag&Drop ToggleSwitch
Move toggle siwtch
Observe
![image](https://user-images.githubusercontent.com/2246331/60806946-a8b99380-a184-11e9-8850-0cd42323e18e.png)

**Comment by wszczepanski97** [comment]
The problem of elements like toggleswitch or slider is that they have more complex construction that span and DE finds a selected element by position and **data-id attribute**.  

Toggleswitch widget has a container that includes handler and input.  

When you drag and drop toggleswitch to template and look in html, you can see that input inside widget has data-id. 
![beforeSave](https://user-images.githubusercontent.com/31214439/60824859-b8e46980-a1aa-11e9-88e6-ade8e9f9e75a.png)


After save it changes and container which includes input and handler gets data-id. 
![afterSave](https://user-images.githubusercontent.com/31214439/60824881-c1d53b00-a1aa-11e9-8e95-10eda9065a36.png)

As I see DE finds a selected element by position and data-id, so I think this is the problem.

**Comment by wszczepanski97** [comment]
Resolved by #148
