### ISSUE TITLE
Slider: wrong height after resizing

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#119]
1) Latest WATT
2) create sample WEB TAU based project
2) move slider from tray to design area
3) move it to center area
4) change size - especially for height
5) resize height to the smallest as small as possible
Observe:

![image](https://user-images.githubusercontent.com/2246331/60809201-66935080-a18a-11e9-894c-adb1ffb3fe22.png)

**Comment by wszczepanski97** [comment]
First of all, slider must have blocked a possibility to resize vertically - it should be resize only in horizontal.
I changed a function setResizable from interaction.js to achieve this state.
Secondly, when slider is resized, it drops his width and I need to research why it behaves like this.

**Comment by lslachciak** [comment]
@wszczepanski97 could you make separate PR one for vertical lock and second one for other issues so we can have issue fixed partially sooner.

**Comment by wszczepanski97** [comment]
@lslachciak sure, I will make it soon

**Comment by wszczepanski97** [comment]
Resizing for slider is now available only in horizontal direction. 
This task is divided on two others: #215 and #213

**Comment by lslachciak** [comment]
This issue is no longer valide. Fixed
