### ISSUE TITLE
Drop down widget has incorrect height

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#120]
1. Create sample app project TAU based
2. Open DE
3. D&D Dropdown Menu widget
4. Observe: - strange height of widget

![image](https://user-images.githubusercontent.com/2246331/60811266-2b475080-a18f-11e9-9237-2281d930a021.png)

**Comment by wszczepanski97** [comment]
Resolved by #120

**Comment by lslachciak** [comment]
Works perfectly
