### ISSUE TITLE
Circle artifacts

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#121]
Reproduction

1. Launch WATT
2. Create TAU based app
3. Run DE and select slider
4. Resize slider and move. Repeat few times
Observe: circle artifacts
![image](https://user-images.githubusercontent.com/2246331/60815758-96495500-a198-11e9-960f-2aa5745619a3.png)

**Comment by hsiwkin** [comment]
This PR: https://github.com/Samsung/TAU-Design-Editor/pull/220 resolves the issue.

**Comment by lslachciak** [comment]
no circle artifacts now
