### ISSUE TITLE
code.tizen.org - example - Index Scrollbar not working

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#123]
1. Open
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fmobile%2FUIComponents%2Fcomponents%2Fnavigationelements%2Findexscrollbar.html
2. Click on letters, numbers on the right side
3. Observe: no scrolling occurs

**Comment by wszczepanski97** [comment]
Repaired by #147

**Comment by lslachciak** [comment]
works well
