### ISSUE TITLE
code.tizen.org - example: Navigation bar not displayed properly

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#124]
Visit:
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fmobile%2FUIComponents%2Fcomponents%2Fnavigationelements%2Fpanel%2Findex.html
Observe:
view is broken

![image](https://user-images.githubusercontent.com/2246331/60891567-d6bed680-a25d-11e9-9d9f-c67be2736602.png)

compare with:
https://samsung.github.io/TAU/examples/1.0/examples/mobile/UIComponents/components/navigationelements/panel/index.html

**Comment by wszczepanski97** [comment]
Repaired by #147

**Comment by lslachciak** [comment]
issue will be verified after code.tizen.org update

**Comment by lslachciak** [comment]
Issue works OK, but new issue was observed on navigation bar: https://github.com/Samsung/TAU-Design-Editor/issues/166
