### ISSUE TITLE
code.tizen.org - example - Popup - not displayed properly #195 

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#125]
Visit:
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fmobile%2FUIComponents%2Fcomponents%2Fpopup%2Fpopup.html
Observe:
List items are spread
![image](https://user-images.githubusercontent.com/2246331/60891463-a9722880-a25d-11e9-952c-82f7f81465db.png)

Compare to:
https://samsung.github.io/TAU/examples/1.0/examples/mobile/UIComponents/components/popup/popup.html

**Comment by lslachciak** [comment]
This may be connected to https://github.com/Samsung/TAU-Design-Editor/issues/128

**Comment by lslachciak** [comment]
Fixed in https://github.com/Samsung/TAU-Design-Editor/issues/128

**Comment by pkaczmarczy** [comment]
The #145 PR has been already merged.
