### ISSUE TITLE
code.tizen.org - example - Radio button issue

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#126]
1.
Open
 https://code.tizen.org/demos?path=1.0%2Fexamples%2Fmobile%2FUIComponents%2Fcomponents%2Fcontrols%2Fradio.html
2. Click any of the radio samples
3. Observe:
"The Active Radio text" is not updated

![image](https://user-images.githubusercontent.com/2246331/60892851-1dadcb80-a260-11e9-86af-b6dffb49a9cb.png)

**Comment by korneliakobiela** [comment]
It was solved by Samsung/TAU-Design-Editor/pull/147

**Comment by lslachciak** [comment]
I'll make verification after next code.tizen.org update (planned on Wednesday, 17th)

**Comment by lslachciak** [comment]
@korneliakobiela I still observe an issue but only on the first run (without click), i.e. when you start preview of app
![image](https://user-images.githubusercontent.com/2246331/61441908-deaa0500-a946-11e9-83fd-cbc12ae84d83.png)

**Comment by hsiwkin** [comment]
PR resolving this issue: https://github.com/Samsung/TAU/pull/249

**Comment by lslachciak** [comment]
@hsiwkin gh-pages branch of TAU was not updated

**Comment by lslachciak** [comment]
issue fixed
