### ISSUE TITLE
code.tizen.org - example - gallery not working

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#127]
1. Visit
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fmobile%2FUIComponents%2Fcomponents%2Fgallery%2Fgallery.html
2. Try to slide
Observe:
- unable to slide image

**Comment by pkaczmarczy** [comment]
PR has been merged

**Comment by lslachciak** [comment]
Issue still is reproducible on
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fmobile%2FUIComponents%2Fcomponents%2Fgallery%2Fgallery.html

**Comment by pkaczmarczy** [comment]
Yes, but helper is not created due to fail in library-creator.
AWS is running Design Editor with this bug. On my local machine everything is correct.

Bug:
![Screenshot from 2019-07-19 13-54-39](https://user-images.githubusercontent.com/38784474/61533987-a847b500-aa2e-11e9-8116-9ff529701fb0.png)

**Comment by lslachciak** [comment]
OK, I'll verify it with next code.tizen.org update

**Comment by lslachciak** [comment]
works well
