### ISSUE TITLE
code.tizen.org - example - list elements are not under each other

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#128]
1 Open
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fmobile%2FUIComponents%2Fcomponents%2Fnavigationelements%2Ftabs%2Ftabs_text_only_4.html
2. Go To Live preview
3. Observe:
List elements are not under each other
![image](https://user-images.githubusercontent.com/2246331/60949291-2a303380-a2f5-11e9-93b1-8988f5dca572.png)

**Comment by lslachciak** [comment]
@pkaczmarczy please check if your PR fixes also issue https://github.com/Samsung/TAU-Design-Editor/issues/125

**Comment by lslachciak** [comment]
I can confirm that PR https://github.com/pkaczmarczy/TAU-Design-Editor/commit/70f86cea3ee500b73fecbe1f438ffe096f8f7715 fixes this issue and #125 too

**Comment by pkaczmarczy** [comment]
The PR has been already merged
