### ISSUE TITLE
code.tizen.org - example - Date Picker - not working

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#132]
Visit:
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fcontrols%2Fdate-picker.html
Observe:
![image](https://user-images.githubusercontent.com/2246331/60969789-b60b8500-a320-11e9-9e6b-c5ce29ecd753.png)

**Comment by wszczepanski97** [comment]
Repaired by #147

**Comment by lslachciak** [comment]
This issue is fixed but new occurs - after clicking set blank page is shown
