### ISSUE TITLE
code.tizen.org - example - Marquee - no marquee

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#133]
Open
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fcontrols%2Fmarquee%2Findex.html
Observe: No Marquee animation
![image](https://user-images.githubusercontent.com/2246331/60972589-d9d1c980-a326-11e9-9c0a-7386e7381ca6.png)

**Comment by wszczepanski97** [comment]
I don't see a problem, marquee animation works. 
Probably, #147 repairs this issue.

**Comment by lslachciak** [comment]
woks good
