### ISSUE TITLE
code.tizen.org - example - marquee - scrollbar is visible

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#134]
Open
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fcontrols%2Fmarquee%2Findex.html

Observe:
scrollbar is visible

**Comment by lslachciak** [comment]
@hsiwkin scrolbar is still visible
![image](https://user-images.githubusercontent.com/2246331/61529752-74ff2900-aa22-11e9-812c-1d16fa745e99.png)

**Comment by hsiwkin** [comment]
Styles are not loaded due to fail in library-creator.
AWS is running Design Editor with this bug. On my local machine everything is correct.

Bug:
https://user-images.githubusercontent.com/38784474/61533987-a847b500-aa2e-11e9-8116-9ff529701fb0.png

**Comment by lslachciak** [comment]
Scrollbar is not visible now
