### ISSUE TITLE
code.tizen.org - example - numberpicker - no Set button

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#135]
Visit
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fcontrols%2Fnumberpicker%2Fsimple.html
Observe:
no Set button
![image](https://user-images.githubusercontent.com/2246331/60972974-94fa6280-a327-11e9-8abf-281c1f2aea8e.png)

**Comment by hsiwkin** [comment]
This issue is no longer present on the current version (from master branch) of the app

**Comment by lslachciak** [comment]
issue will be verified after code.tizen.org update

**Comment by lslachciak** [comment]
works OK but issue https://github.com/Samsung/TAU-Design-Editor/issues/175 exists
