### ISSUE TITLE
code.tizen.org - example - Page Indicator - broken view

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#136]
Visit:
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fcontrols%2Findicator%2Fpageindicator_circle.html
Observe:
![image](https://user-images.githubusercontent.com/2246331/60973547-caec1680-a328-11e9-8d29-022fd8f35e1b.png)

**Comment by lslachciak** [comment]
May be related to https://github.com/Samsung/TAU-Design-Editor/issues/138

**Comment by wszczepanski97** [comment]
Repaired by #147

**Comment by lslachciak** [comment]
thank you
issue will be verified with next code.tizen.org update

**Comment by lslachciak** [comment]
works good
