### ISSUE TITLE
code.tizen.org - wearable - Popup - UI broken after

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#137]
Reproduction steps
1. Open
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fpopup%2Fpopup.html
2. Go To Live Preview
3. CLick General
4. Click OK button
5. Observe

![image](https://user-images.githubusercontent.com/2246331/60974134-d3911c80-a329-11e9-9271-361da04e00bf.png)

**Comment by korneliakobiela** [comment]
Today I've started working on this problem. I don't know what exactly is causing this issue but I can see some symptoms. After submitting the pop-up, the document showed into the iframe is changing from `temporary-preview.html` to `popup.html`. In other words, the copy made especially for preview is replaced by the original document.

**Comment by korneliakobiela** [comment]
I've recognized the cause of the problem. In this example, there are so many places where the filename `popup.html` is hardcoded. So while the pop-up is opened, the page is changed to popup.html from temporary-preview.html.
Now I will be looking for a good solution. I have an idea about solve this problem. Change every occurrence of <file_name>.html to temporary-preview.html before showing the preview. I have to get known if it doesn't spoil anything.

**Comment by korneliakobiela** [comment]
I've started to code the proper solution in #165 PR. It looks that it works, but need some refactoring. 
@lslachciak Can you check for me if there is another example with the analogous problem?

**Comment by lslachciak** [comment]
@korneliakobiela so far I didn't noted similar issue in other cases, but if I find I'll let you know.

**Comment by lslachciak** [comment]
I'll verify this issue with next code.tizen.org update
