### ISSUE TITLE
code.tizen.org - example - section changer - broken view

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#138]
visit:
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fnavcontrols%2Fsectionchanger%2Fhsection.html
observe:
![image](https://user-images.githubusercontent.com/2246331/60975113-a6de0480-a32b-11e9-843a-6f94093d6bb9.png)

**Comment by wszczepanski97** [comment]
Repaired by #147

**Comment by lslachciak** [comment]
will be verified with code.tizen.org update

**Comment by lslachciak** [comment]
works OK
