### ISSUE TITLE
code.tizen.org - wearable - selector - black screen

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#139]
Visit:
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fcontrols%2Fselector%2Fselector.html
Observe:
![image](https://user-images.githubusercontent.com/2246331/60975574-79de2180-a32c-11e9-8fa9-48d53e69fbdf.png)

**Comment by TomaszLukawskiSam** [comment]
@korneliakobiela @pkaczmarczy 
The cause of issue is patch for "main" id of initial page (1fb4cb04bab6b2cecba63564bb67926f53e7a3c8). I try to change this code. The "tizenhwkey" will be triggered when document.location.href will be different then initial URL.

**Comment by TomaszLukawskiSam** [comment]
PR has already merged but for verify result on code.tizen.org we need update WATT.

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
PR resolved the issue.

**Comment by lslachciak** [comment]
I'll make verification after next code.tizen.org update (planned on Wednesday, 17th)

**Comment by lslachciak** [comment]
works ok
