### ISSUE TITLE
Graph,Dimmer widgets are not displayed normally

### ISSUE THREAD

**Issue by pkaczmarczy** [Samsung/TAU-Design-Editor#140]
Widgets are not displayed with older Tizen versions.

Those widgets are available since TAU 1.1. Widgets should be disabled if current TAU version is earlier.

**Comment by lslachciak** [comment]
@pkaczmarczy  could you put this issue to review if all PR are merged?

**Comment by pkaczmarczy** [comment]
PR has been already merged.
