### ISSUE TITLE
 code.tizen.org - Slider - wearable - incorrect UI

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#142]
Visit:
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fcontrols%2Fslider%2Fslider.html
Observe:
![image](https://user-images.githubusercontent.com/2246331/61041123-21615f80-a3d2-11e9-8051-73a894915796.png)

**Comment by wszczepanski97** [comment]
It looks like PR https://github.com/Samsung/TAU-Design-Editor/pull/147 resolve this issue.
When example was loaded first time, slider look like on photo above and in next launches of example looks correct. 
Now, after changes slider looks correct from the beginning

**Comment by lslachciak** [comment]
thank you, issue will be verified with next code.tizne.org update

**Comment by lslachciak** [comment]
works ok
