### ISSUE TITLE
code.tizen.org  - wearable - time picker - no UI

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#143]
Visit:
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fcontrols%2Ftime-picker.html
Observe:
![image](https://user-images.githubusercontent.com/2246331/61041739-22df5780-a3d3-11e9-8166-6f043438e20b.png)

**Comment by wszczepanski97** [comment]
Repaired by #147

**Comment by lslachciak** [comment]
will be checked with next tizen.org update

**Comment by lslachciak** [comment]
issue fixed but another issue exists: https://github.com/Samsung/TAU-Design-Editor/issues/175
