### ISSUE TITLE
code.tizen.org - wearable - virtual list  empty

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#144]
Visit:
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Flist%2Fvirtual%2Fnormal.html
Observe:
![image](https://user-images.githubusercontent.com/2246331/61042970-836f9400-a3d5-11e9-84db-9142ea23aefa.png)

Expected:
See video on: https://developer.tizen.org/development/api-references/web-application?redirect=https://developer.tizen.org/dev-guide/5.0.0/org.tizen.web.apireference/html/ui_fw_api/Wearable_UIComponents/wearable_virtuallist.htm

**Comment by hsiwkin** [comment]
PR: https://github.com/Samsung/TAU-Design-Editor/pull/147 resolved this issue

**Comment by lslachciak** [comment]
I'll make verification after next code.tizen.org update (planned on Wednesday, 17th)

**Comment by lslachciak** [comment]
@hsiwkin issue is fixed but strange items with tags are on the list
see https://github.com/Samsung/TAU-Design-Editor/issues/164

**Comment by hsiwkin** [comment]
I'll check it
