### ISSUE TITLE
DropdownMenu - incorrect image

### ISSUE THREAD

**Issue by pkaczmarczy** [Samsung/TAU-Design-Editor#156]
Current DropdownMenu widget looks different, also it should not have the "new" label.
This is a legacy after iot widgets.

**Comment by korneliakobiela** [comment]
I've made PR https://github.com/Samsung/TAU-Design-Editor/pull/242. It's ready to review and close.

**Comment by lslachciak** [comment]
@pkaczmarczy could you review and clsoe this issue?

**Comment by pkaczmarczy** [comment]
Looks good to me.
