### ISSUE TITLE
Dragged image has height and width 0px

### ISSUE THREAD

**Issue by wszczepanski97** [Samsung/TAU-Design-Editor#161]
1. Create TAU Base Application
2. Drag an image to template.
Dragged image gets height and with equals to 0px(you can see this in attributes panel).

![imageSizeProblem](https://user-images.githubusercontent.com/31214439/61370782-849c3780-a893-11e9-9719-960ca8e03030.png)
![imageproperties](https://user-images.githubusercontent.com/31214439/61370853-a7c6e700-a893-11e9-8ac9-c50d81172bbb.png)

**Comment by lslachciak** [comment]
After PR I verified issue, but additional PR was
Issue works well
