### ISSUE TITLE
ListView - Wearable - not scrolled in Editing mode

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#162]
1. Create an empty project based on wearable UIComponents app
2. Run DE

Observe:
No list scrolling occurs
![image](https://user-images.githubusercontent.com/2246331/61374201-0c863f80-a89c-11e9-80a0-41535ec24062.png)

**Comment by korneliakobiela** [comment]
I think that the problem with scrolling occurs in the whole Design Editor (in design mode).

**Comment by lslachciak** [comment]
@pkaczmarczy you can modify reproduction steps after your PR to WATT

**Comment by pkaczmarczy** [comment]
PR has been already merged.

**Comment by lslachciak** [comment]
PR verified working
