### ISSUE TITLE
code.tizen.org - wearable - virtual list - <a> in the list

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#164]
Visit:
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Flist%2Fvirtual%2Fnormal.html
Observe:
<a> tags on a list
![image](https://user-images.githubusercontent.com/2246331/61378986-dbf7d300-a8a6-11e9-9bf2-66bc5547c22e.png)

**Comment by hsiwkin** [comment]
It looks like TAU issue (or issue in the example file: contents/list/virtual/temporary-preview). It looks like the <a> tags are encoded in there. 
After changing 25-27 lines to this (non encoded form): 
```
		<script id="template-li-1line" type="text">
			<a>${NAME}</a>
   		</script>
``` 
it looks better (a tags are not in plain text)

**Comment by wszczepanski97** [comment]
PR is merged #243

**Comment by lslachciak** [comment]
this change is not available yet in latest code.tizen.org

**Comment by lslachciak** [comment]
code.tizen.org will be updated on Wednesday and this issue will be closed.

**Comment by lslachciak** [comment]
works well
