### ISSUE TITLE
Toggle Slider cannot be dragged 

### ISSUE THREAD

**Issue by hsiwkin** [Samsung/TAU-Design-Editor#172]
Toggle Slider component can't be added to the user's project in DE.

**Comment by hsiwkin** [comment]
The issue is resolved by this PR: https://github.com/Samsung/TAU-Design-Editor/pull/180

**Comment by lslachciak** [comment]
Works OK for mobile.
For wearable I found another issue: https://github.com/Samsung/TAU-Design-Editor/issues/192
