### ISSUE TITLE
Listview cannot be moved

### ISSUE THREAD

**Issue by korneliakobiela** [Samsung/TAU-Design-Editor#174]
## Description
When user appends ListView widget to an existing application, he cannot move it to another place in any way. 
## Technical

- Platform: Both
- Profile: Mobile
- Sample: Tau Base
- Tau version: 1.1.0

## Steps to reproduce
1. Create a new project in Design Editor
2. Add listview to project
3. Append  the list item to this view
3. Open Tree view
4. Mark listview component in the structure tree
5. Try to move it

## Expected behaviour
User is able to move the whole list

## Actual behaviour
User can move only single pieces of the list

**Comment by lslachciak** [comment]
@korneliakobiela could you provide more repro steps or attach sample app?
I tried mobile sample basic and was able to move listview

**Comment by korneliakobiela** [comment]
> I tried mobile sample basic with WATT and was able to move listview
@lslachciak I've updated the Issue description and it still exists, but I am not sure if we are able to fix it easily.

**Comment by korneliakobiela** [comment]
I've done this issue, this works and I close this issue
