### ISSUE TITLE
Scroll is visible in editing mode

### ISSUE THREAD

**Issue by korneliakobiela** [Samsung/TAU-Design-Editor#176]
## Description
Browser scrollbar is visible sometimes in edition mode when elements content is bigger than the container. I think it is strange behaviour especially if we cannot scroll this content in editor mode.

## Technical
TAU version: 1.1.0

## Steps to reproduce
1. Create a new project in Design Editor
2. Add box (div) to its content
3. Append Some widgets to the box. It has to be more of them than box dimensions.
4. Focus box and change its attributes:
    - overflow-y: auto

## Expected behaviour
Not visible scroll bar **OR** working scrollbar that can be scrolled **OR** some other way to manipulate the content of the box
## Actual behaviour
Visible scrollbar which isn't operational.
![image](https://user-images.githubusercontent.com/18300603/62043089-d6cc4980-b1ff-11e9-9ce3-a73603c44a83.png)

**Comment by lslachciak** [comment]
@korneliakobiela I'm trying to reproduce this issue but need more details about repro steps

**Comment by korneliakobiela** [comment]
@lslachciak I've updated the issue description.

**Comment by lslachciak** [comment]
@korneliakobiela thank you, I reproduced issue

**Comment by hsiwkin** [comment]
I'll try to make this list scrollable & editable in the edit mode on focus, after being clicked (probably by temporarily modifying its styles).

**Comment by korneliakobiela** [comment]
Looks and works well. I've checked it
