### ISSUE TITLE
[WATT] Can't save text in the HTML assistant

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU-Design-Editor#183]
## Technical
Can't save the text in the HTML assistant
## Steps to reproduce
1. Create a new project in Design Editor of WATT
2. Open the html file in DE
3. Select HTML element
4. Click HTML assistant icon
5.  Edit text in the HTML Assistant and then click HTML assistant icon

## Expected behaviour
edit text is save.

## Actual behaviour
edit text isn't save.

**Comment by lslachciak** [comment]
we will take care of it with priority

**Comment by hsiwkin** [comment]
The issue will be resolved by this PR: https://github.com/Samsung/TAU-Design-Editor/pull/193/files

**Comment by lslachciak** [comment]
@singa2000 
I confirm that this issue was fixed
Please close this issue if no objections.
