### ISSUE TITLE
[WATT]Javascript Assistant Wizard can't be select "Use Exist Var"

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU-Design-Editor#184]
## Description
 Javascript Assistant Wizard can't be select "Use Exist Var"
## Steps to reproduce
1. Create a new project in Design Editor
2. Open the  Javascript Assistant Wizard
3. Select the HTML items(like button) and set the "Variable Name" by "btn" in "Selector"
4. Select the "Event Listener" in the Javascript Assistant Wizard

## Expected behaviour
Can select the "Use Exist Var"
## Actual behaviour
Can't select the "Use Exist Var"

**Comment by wszczepanski97** [comment]
I made a PR #258 
The problem is that after save, elements change their data-ids and elements from weakmap are not equal to elements in iFrame, so they cannot be found and exist variables are not found.

**Comment by singa2000** [comment]
The patch is merge and it's good working in WATT and VSCode
