### ISSUE TITLE
Not able to enter DE mode

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#187]
## Technical Description
Not able to enter DE mode #454

## Steps to reproduce
Create sample TUA Base mobile project
Go to DE mode (icon on right)
Switch to Live Preview (icon on left)
Go to Code Editing mode (icon on right)
Go to DE mode (icon on right)
## Expected behaviour
DE me is on
## Actual behaviour
DE stays in broken live preview mode

**Comment by grzegorz-czajkowski** [comment]
Patch merged.
