### ISSUE TITLE
Preview is on the left side when Structure tree view is open in desing mode

### ISSUE THREAD

**Issue by korneliakobiela** [Samsung/TAU-Design-Editor#189]
## Technical
Platform: Both
## Description
Preview is on the left side when Structure tree view is open in the desing mode. Screens with an opened Tree view.
![image](https://user-images.githubusercontent.com/18300603/61520387-5bec7d00-aa0e-11e9-8c99-fb257c0a3cce.png)
![image](https://user-images.githubusercontent.com/18300603/61520456-850d0d80-aa0e-11e9-9d5c-f4e82d80bbfe.png)
Screen with closed one
![image](https://user-images.githubusercontent.com/18300603/61520558-c1406e00-aa0e-11e9-8522-22cbc87c5343.png)
## Steps to reproduce
1. Create a new project in Design Editor
2. Open Structure Tree view
3. Open Preview

## Expected behaviour
Previewed application frame in the centre of the screen.
## Actual behaviour
Previewed application screen on the left side.

**Comment by wszczepanski97** [comment]
PR #255 is resolving this problem

**Comment by korneliakobiela** [comment]
Looks well :small_airplane:
