### ISSUE TITLE
Toggle Slider - wearable - look similar to toggle switch

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#192]
#Description
There is no difference between toggle switch and toglle slider for on wearable in DE

## Steps to reproduce
1. Create a new project in Design Editor for wearable
2. DnD Toggle switch
2. DnD Toggle slider

## Expected behaviour
Toggle switch differ from toggle slider
## Actual behaviour
Toggle switch doesn't differ from toggle slider

**Comment by TomaszLukawskiSam** [comment]
To resolve the issue we need also TAU 1.1 update in sample apps in WATT.

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
The TAU is updated in sample apps. I think that issue can be close.

**Comment by lslachciak** [comment]
works well
