### ISSUE TITLE
Graph widget - mobile - not visible in DE

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#196]
## Description
Graph widget is not visible in DE
## Steps to reproduce
1. Create a new project in Design Editor - Mobile - Sample TAU app
2. Add graph widget
## Expected behaviour
1. Graph widget is visible
## Actual behaviour
2. Graph widget is not visible
![image](https://user-images.githubusercontent.com/2246331/61534775-c7dfdd00-aa30-11e9-8266-396068db9b69.png)

**Comment by lslachciak** [comment]
I still can't see graph widget (latest WATT + DE)
![image](https://user-images.githubusercontent.com/2246331/61710991-4602f300-ad53-11e9-938c-954ba35b81a0.png)

**Comment by hsiwkin** [comment]
I've checked it and the issue is no longer present on the samples generated by the newest version of WATT (after this commit: 596b27f58d3e04a6df27b0d6da3c10a28c4ca2f9 'Change use tau bundled with external libraries in samples'). 
It's because the new samples contain bundled TAU lib.

**Comment by lslachciak** [comment]
works
