### ISSUE TITLE
Graph widget - wearable - graph widget is not visible in DE and Live preview

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#197]
## Description
Graph widget - wearable - graph widget is not visible in DE and Live preview

## Steps to reproduce
1. Create a new wearable project in Design Editor
2. Add Graph widget
3. Run DE Live preivew
## Expected behaviour
Graph widget is visible
## Actual behaviour
Graph widget is not visible both in Live Preview as well as in DE

**Comment by lslachciak** [comment]
Ma be partially related to https://github.com/Samsung/TAU-Design-Editor/issues/196

**Comment by lslachciak** [comment]
@pkaczmarczy this was fixed with your PR: https://github.com/Samsung/WATT/pull/156

**Comment by lslachciak** [comment]
Unfortunatelly graph widget for wearable is still not visible
![image](https://user-images.githubusercontent.com/2246331/61711288-fa9d1480-ad53-11e9-9eba-d6b0e5775ccc.png)

**Comment by hsiwkin** [comment]
The issue will be resolved by this PR: https://github.com/Samsung/TAU-Design-Editor/pull/236/files

**Comment by lslachciak** [comment]
Fixed, works
