### ISSUE TITLE
There is no possibility to remove background color in attributes panel

### ISSUE THREAD

**Issue by korneliakobiela** [Samsung/TAU-Design-Editor#198]
## Technical
Platform: Both
## Description
Background-color can be set but cannot be removed or set as transparent or semi-transparent.
## Steps to reproduce
1. Create a new project in the Design Editor.
2. Add some widget.
3. Set background colour

## Expected behaviour
Some way to set semi-transparent colours (RGBA) and remove background colour.
## Actual behaviour
No way to do it. Background once created always been in application.

**Comment by wszczepanski97** [comment]
PR #332 is merged. I close an issue.
