### ISSUE TITLE
slider - after save slider change its look

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#215]
## Technical
slider - after save slide change its look

## Steps to reproduce
1. Create a new project in Design Editor (wearable TAU Basic)
2. d&D slider
3. Save
## Expected behaviour
No change UI
## Actual behaviour
UI changed

**Comment by wszczepanski97** [comment]
Issue can be closed. I create a new one #238 cause problem with Slider now is another. After save it works ok.

**Comment by lslachciak** [comment]
Issue fixed, than you
