### ISSUE TITLE
JS Assistant drag&drop is triggered when JS Assistant is closed

### ISSUE THREAD

**Issue by hsiwkin** [Samsung/TAU-Design-Editor#221]
## Technical
Platform: Both

## Description
DE tries to open JS Assistant drag&drop wizard while dragging the component when JS Assistant is closed

## Steps to reproduce
1. Launch WATT
2. Create TAU based app
3. Run DE and select slider
4. Resize slider and move. Repeat few times
5. Observe: warning saying that JS Assistant drag & drop functionality is not implemented

## Expected behaviour
The warning shouldn't be printed in the console as DE shouldn't try to open JS Assistant wizard while dragging components while JS Assistant is closed.

## Actual behaviour
There is the warning printed in the console saying that JS Assistant drag & drop functionality is not implemented.

**Comment by hsiwkin** [comment]
It's resolved by this PR: https://github.com/Samsung/TAU-Design-Editor/pull/229

**Comment by lslachciak** [comment]
Fixed, thank you
