### ISSUE TITLE
Javascript Assistant Wizard can't open (WATT Mobile)

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU-Design-Editor#223]
## Description
 Javascript  Assistant -> Javascript Assistant Wizard can't open
 This issue is happen latest code.
 By 0.6.4 Release, it's good working

## Steps to reproduce
1. Create a new project in Design Editor
2.  Javascript  Assistant 
3. Select the Insert Code 

## Expected behaviour
 Javascript Assistant Wizard can open
## Actual behaviour
 Javascript Assistant Wizard can't open

**Comment by lslachciak** [comment]
Quick fix for this issue is here https://github.com/Samsung/TAU-Design-Editor/pull/226
but this will revert fix for circle artifacts https://github.com/Samsung/TAU-Design-Editor/issues/121

**Comment by hsiwkin** [comment]
PR: https://github.com/Samsung/TAU-Design-Editor/pull/229 resolves this issue

**Comment by lslachciak** [comment]
Issue fixed
