### ISSUE TITLE
DE Flickering while reopen

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#230]
## Technical
WATT
## Description
Flickering occurs when
- opening DE again
## Steps to reproduce
1. Create a new project in Design Editor WATT, mobile based
2. Go to DE
3. Go to Code editor
4, Go to DE
## Expected behaviour
No flickering
## Actual behaviour
Flickering (point 4 and 6)

**Comment by korneliakobiela** [comment]
The reason for this problem is the update method in the design-editor-element module. This method is updating a view in Design Mode in every file update.

**Comment by korneliakobiela** [comment]
Today I've made some editions in DE initialization. It prevents flickering during reopen Design Editor but doesn't work well while saving.

**Comment by korneliakobiela** [comment]
I switch off refreshing during saving. Now the flickering on save doesn't occur but on reopen occurs randomly.

**Comment by korneliakobiela** [comment]
I've fixed it on Save. Unfortunately changing this action during reopen DE is a very complicated issue so we discussed to move it to 2.0
