### ISSUE TITLE
toggle slider - mobile - looks strange

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#231]
## Technical
WATT, mobile
## Steps to reproduce
1. Create a mobile new project in Design Editor
2. D&D toggle slider

## Expected behavior
Toggle slider similar to this on the widget list
## Actual behavior
![image](https://user-images.githubusercontent.com/2246331/61720934-f5e25b80-ad67-11e9-94be-ded16a2208e9.png)

**Comment by TomaszLukawskiSam** [comment]
I cannot reproduce the issue.

**Comment by lslachciak** [comment]
Issue no longer reproducible
