### ISSUE TITLE
TextInput: Widget cannot be moved properly

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU-Design-Editor#234]
## Technical
Widget template has changed - now widget is placed with data-outside-div="true". 

## Description
During widget move 

## Steps to reproduce
1. Create a new project in Design Editor
2. Insert text input
3. Try to move text input

## Expected behaviour
Whole widget are properly moved.

## Actual behaviour
Widget is moved but inner structure of widget is changing also.

**Comment by lslachciak** [comment]
@TomaszLukawskiSam this PR resolves this issue https://github.com/Samsung/TAU-Design-Editor/pull/84 ?

**Comment by korneliakobiela** [comment]
@TomaszLukawskiSam is this issue done?

**Comment by TomaszLukawskiSam** [comment]
@korneliakobiela 
All tasks in this issue are done. We can close the issue.
