### ISSUE TITLE
[Mobile] Slider resize is not taking circle handler position into account

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#244]
## Technical
WATT -> Mobile --> TAU Basic app
## Description
Slider resize is not taking circle handler position into account
## Steps to reproduce
1. Create a new project in Design Editor
2. D&D slider
3. Resize slider
## Expected behavior
Position of circle handler is changing according to the slider width
## Actual behavior
Position of circle handler is not changing causing visual issue like

![image](https://user-images.githubusercontent.com/2246331/62027749-ceafe200-b1de-11e9-96c6-a9557835667c.png)

**Comment by pkaczmarczy** [comment]
PR: https://github.com/Samsung/TAU-Design-Editor/pull/294

**Comment by lslachciak** [comment]
@pkaczmarczy can we close this issue ?
looks like slider resize is working now

**Comment by pkaczmarczy** [comment]
Yes, PR has been already merged. Sorry, I didn't change the labels.

**Comment by lslachciak** [comment]
works fine
