### ISSUE TITLE
[VSCode] [Wearable] Graph widget not visible in Live Preview

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#251]
## Technical
VSCode Wearable
## Description
[VSCode] [Wearable] Graph widget not visible in Live Preview
## Steps to reproduce
1. Create a new TAU Base wearable sample app in WATT
2. Open it in DE for VSCode
3. Add Graph widget
4. Run LivePReview
5. Observe
## Expected behaviour
Graph widget visible
## Actual behaviour
![image](https://user-images.githubusercontent.com/2246331/62273977-29477900-b43f-11e9-85a4-c43a1b0958c7.png)

**Comment by hsiwkin** [comment]
It works on the current version of DE.
I've checked on this example: 
[5d42ed167360d751b8e5e1de.zip](https://github.com/Samsung/TAU-Design-Editor/files/3457032/5d42ed167360d751b8e5e1de.zip)

**Comment by lslachciak** [comment]
wokring now
