### ISSUE TITLE
[VSCode] JS Assistant Wizard not working

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#252]
## Technical
VSCode
## Description
[VSCode] JS Assistant Wizard not working
## Steps to reproduce
1. Open project in DE VSCode
2. Select an element
3. Run JS Assistant 
4. Click Insert Code icon
5. Click Variable Name field
## Expected behaviour
Able to edit edifield
## Actual behaviour
Not able to edit field
![image](https://user-images.githubusercontent.com/2246331/62275065-6a408d00-b441-11e9-8b7a-618ba1ac40b4.png)

**Comment by hsiwkin** [comment]
While working on this issue I've encountered problems with debugging source files and printing conosle.log (debug console is blank in the current 1.36.1 version of VSC). I've created an Issue for that on their github: https://github.com/microsoft/vscode/issues/78515

**Comment by hsiwkin** [comment]
PR: https://github.com/Samsung/TAU-Design-Editor/pull/257/files (still in progress)
