### ISSUE TITLE
[Mobile/Wearable] Can't add the Text, Image widgets in the Header 

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU-Design-Editor#261]
## Technical
WATT, VSCode
(by design editor PR https://github.com/Samsung/TAU-Design-Editor/issues/230)
I use WATT Sample for TAU_1.1_Base_Mobile (TAU library is 1.1.0)
## Description
I can't add the Text, Image widgets in the Header.
I just can add the button, Toggle switch widgets in the Header
## Steps to reproduce
1. Create a new project in Design Editor
2. Drag&Drop the Text, Image widgets in the Header.

## Expected behaviour
 Can add the Text, Image widgets in the Header 
## Actual behaviour
Can't add the Text, Image widgets in the Header

**Comment by korneliakobiela** [comment]
PR was merged, please review it

**Comment by singa2000** [comment]
I can add the text.
But can you add the image to Header?
I can't do it by your PR.
So I update the https://github.com/Samsung/TAU-Design-Editor/pull/295

**Comment by korneliakobiela** [comment]
I think this issue is done by PR #295 and #285.
