### ISSUE TITLE
[Mobile] I can't add the Container->Header widget in new page

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU-Design-Editor#262]
## Technical
VSC
(by design editor PR #230)
I use WATT Sample for TAU_1.1_Base_Mobile (TAU library is 1.1.0)
## Description
I can't add the Container->Header widget in new empty page
## Steps to reproduce
1. Create a new project in Design Editor
2. New Page -> create Empty page
3. Drag&Drop the Widget pannel-> Container->Header widget in new empty page
## Expected behaviour
Can add the Header widget
## Actual behaviour
Can't add the Header widget

**Comment by hsiwkin** [comment]
It looks like there is an issue with _onSetNewGuide function in guide.js (it seems to have a problem with working properly when a component has to be placed in the current container's parent). 
I'm in the middle of debugging it (it's old and large function so it takes time to understand and fix it).

**Comment by hsiwkin** [comment]
I've partially refactored guide.js during work on this case but this issue isn't still resolved. 
As I've mentioned above this issue occurs most probably due to errors in guide.js code.

**Comment by korneliakobiela** [comment]
I've made PR with changes and it works. But I think we need to strong refactor Design Editor Core elements like a guide, attributes etc.

**Comment by korneliakobiela** [comment]
This PR was merged. Can you review it?

**Comment by singa2000** [comment]
It's good working. Thanks
