### ISSUE TITLE
Improve Attribute-> Box Models input value

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU-Design-Editor#266]
## Technical
WATT/ VSCode

## Description
1. box shadow : now default value is blank. Default value have to set.
2. border: It is difficult to recognize what value should be put in the first input field.
               It need to guide (integer or range etc)
3. border radius:It is difficult to recognize what value should be put in the  input field.
               It need to guide (integer or range etc)
==> There is a description of each property and range when  mouse is over
4. Set the border value and Save -> Select the widget in Template-> Open again the Box Model
   : The input value is disappear. The set value should be remaind.
5. Border default color is black, but the border of widget color is not black.
    Need to change the border default color.

## Steps to reproduce
1. Create a new project in Design Editor
2. Select the Attributes and open the Box Model tab

## Expected behaviour
It should be intuitive for using the Attribute->Box Model
==> There is a description of each property and range when mouse is over

## Actual behaviour
It is difficult to recognize what value should be put in the  input field.

**Comment by pkaczmarczy** [comment]
I have assigned incorrect issue to myself, sorry.

**Comment by korneliakobiela** [comment]
Summarizing this task consist of smaller issues:

- [ ] Add placeholders to inputs where value is difficult to recognize
- [ ] Add properties description on mouse over above inputs elements
- [ ] Get real default values on inputs
- [ ] Get values after saving documents

**Comment by korneliakobiela** [comment]
I've done placeholders today
![image](https://user-images.githubusercontent.com/18300603/63704145-ae4d6480-c82a-11e9-9561-2ef997c699e3.png)

**Comment by korneliakobiela** [comment]
Now I was working on hints on mouse over the inputs. The screenshot below shows cursor and the hint
![Screenshot from 2019-08-27 14-20-04](https://user-images.githubusercontent.com/18300603/63771285-2a04eb00-c8d7-11e9-9854-612c602860d4.png)

**Comment by korneliakobiela** [comment]
I've investigated the next part of the problem. It turnt out more difficult that I expected ealier. I separate this issue into smaller ones #302 and #303. So I think we can close this issue.
