### ISSUE TITLE
Remove the "Widget options" Attribute-> Element

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU-Design-Editor#267]
## Technical
WATT/VSC
## Description
Remove the "Widget options" Attribute-> Element if it don't needed

## Steps to reproduce
1. Create a new project in Design Editor
2. Open the Attributes tab and select the Element

## Expected behaviour
Unnecessary items should be deleted

## Actual behaviour
There is the "Widget options" but it don't use

**Comment by singa2000** [comment]
@TomaszLukawskiSam @korneliakobiela 
Attribute -> Element -> Widget options are using?
If there is not using, I'll remove it.

**Comment by TomaszLukawskiSam** [comment]
> @TomaszLukawskiSam @korneliakobiela
> Attribute -> Element -> Widget options are using?
> If there is not using, I'll remove it.

We can remove this property.

**Comment by singa2000** [comment]
patch is merged
