### ISSUE TITLE
HTML Assistant can't close after losing the focus

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU-Design-Editor#269]
## Technical
WATT/ VSCode

## Description
HTML Assistant can't close after losing the focus

## Steps to reproduce
1. Create a new project in Design Editor
2. Drag&Drop the Text and Open the HTML Assistant
3. Mouse focus elsewhere except on HTML Assistant and Template and click
4. Again "HTML Assistant" button for close the HTML Assistant window

## Expected behaviour
Close the HTML Assistant window

## Actual behaviour
HTML Assistant can't close after click the mouse outside the HTML Assistant or Template

**Comment by korneliakobiela** [comment]
Issue is done.

**Comment by singa2000** [comment]
Dear Korrnelia
Would you check HTML Assistant and JavaScript Assistant after apply the https://github.sec.samsung.net/HighPerformanceWeb/VSC-Design-Editor/pull/75, please?
It looks Some feature is not working after merge the VSC-Design-Editor/pull/75.

**Comment by korneliakobiela** [comment]
Dear Hwang, 
I can't reproduce this issue. Please check that your VSC Design Editor is up to date `git pull` and then check its submodule is up to date. Then it works for me.

**Comment by singa2000** [comment]
ok. The HTML Assistant is good working.
We can be close issue.
