### ISSUE TITLE
In the Preview, replace button to return to Desgin Editor

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU-Design-Editor#270]
## Technical
WATT/ VSCode
## Description
In the Preview, the button to return to Desgin Editor is  not intuitive
## Steps to reproduce
1. Create a new project in Design Editor
2. Go to Preview
3. Try to comeback to Design Editor by selecting the "Play" button

## Expected behaviour
The button to go to Design Editor in Preview needs to be intuitive.
Now it looks like a button for Back button to go to Design Editor.

## Actual behaviour
It's not intuitive for Design Editor in Preview

**Comment by singa2000** [comment]
We'll discuss with UX team about the proper icon image

**Comment by wszczepanski97** [comment]
PR #318 is made.

**Comment by wszczepanski97** [comment]
PR #318 is merged. We can close an issue.

**Comment by singa2000** [comment]
It's good. Thanks~
