### ISSUE TITLE
After change the Graph widget Style, the position is recover

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU-Design-Editor#271]
## Technical
WATT/VSC

## Description
After change the Graph widget Style, the position is recover

## Steps to reproduce
1. Create a new project in Design Editor
2. Drag&Drop the Graph widget
3. move the position to below
4. Select the Graph and Attribute -> Style -> Change to "bar chart"

## Expected behaviour
Keeping the position

## Actual behaviour
Move the position

**Comment by pkaczmarczy** [comment]
Work in progress. I have to fixup few more things before it would be finish and clean up the commit.
https://github.com/pkaczmarczy/TAU-Design-Editor/tree/issue-271-graph-is-moved-after-changing-pre-defined-style

**Comment by pkaczmarczy** [comment]
The PR fixes the problem with graph.

To fully replace previous functions we need to:
- Add way of defining child elements inside template
- Implement mechanism of filling template content based on element content (see listelement components)
- Convert old-style templates to new definitions

Also graph has problems with dynamicly changing chart type (without destroying widget as previously).

**Comment by pkaczmarczy** [comment]
PR has been merged.
Graph widget change will be visible after TAU update in WATT.

**Comment by lslachciak** [comment]
@pkaczmarczy could you check with @TomaszLukawskiSam TAU update?

**Comment by lslachciak** [comment]
@pkaczmarczy I updated TAU in WATT
https://github.com/Samsung/WATT/commit/d7f9891752c9f0c1a1d91bee73e1c9ba829e3243

**Comment by lslachciak** [comment]
@singa2000 I tested this change with latest TAU 1.1.4 project in VSC,
after grapgh type change no movement occurs

**Comment by singa2000** [comment]
I test latest TAU 1.1.4 project in VSC,
After graph type change Attribute->Widget Options-> Graph Type no movement occurs.
But Attribute -> Style , I can't select the Time series or Multiple series.
The Attribute Style is same with Attribute Widget Option Graph Type?
If so, would you remove the Attribute Style of Graph widget?

**Comment by lslachciak** [comment]
@singa2000 issue you mention was reported for TAU
https://github.com/Samsung/TAU/issues/347
problem is with refreshing wiget
Temporary I disabled graph styles in 
PR https://github.com/Samsung/TAU-Design-Editor/pull/363

**Comment by lslachciak** [comment]
DE PR 363 merged

**Comment by singa2000** [comment]
We can close the issue
