### ISSUE TITLE
Dropdown widget value don't  immediately reflected in Template

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU-Design-Editor#272]
## Technical
WATT / VSC
## Description
Dropdown widget don't  immediately reflected in Template after change the value.

# Steps to reproduce
1. Create a new project in Design Editor
2. Drag&Drop the DropDown widget
3. Attribute -> Element -> Add items

## Expected behaviour
Immediately reflected in Template if change the value before Preview or Save
In case of Graph widget, if you change the "Graph X label"," Graph Y label" it apply in the Template.

## Actual behaviour
Dropdown widget don't  immediately reflected in Template

**Comment by TomaszLukawskiSam** [comment]
All changes have been already merged. I think the issue can be close.

**Comment by singa2000** [comment]
It's good working.
Thanks
