### ISSUE TITLE
Cannot run the js code wizard in WATT

### ISSUE THREAD

**Issue by hyundukkim** [Samsung/TAU-Design-Editor#275]
## Technical
 WATT/VSC
## Description
I cannot see code wizard even pressing </> button in IDE after adding button element
## Steps to reproduce
1. Create a new project in Design Editor
2. Web Application > Sample > Mobile > General > TAU Base
3. Click 'Monitor' shaped icon at the right side of screen
4. Click button element in the list and drag and drop on page
5. Click the button element in screen to give a focus
6. Click 'Javascript Assistant' button in left side
7. Click on empty area of the code area
8. Click Insert Code (</>) button 
## Expected behaviour
As per the gif guide at https://github.com/Samsung/TAU-Design-Editor#features,
it should show code wizard.

## Actual behaviour
Nothing happens even clicking 'Insert Code' button

**Comment by singa2000** [comment]
By checking  latest Design Editor( https://github.com/Samsung/TAU-Design-Editor/issues/277), JS Assistant is good working.
Maybe it was fixed by https://github.com/Samsung/TAU-Design-Editor/pull/257.
