### ISSUE TITLE
[WATT]New Page Wizard can't see the "Accept", "Cancel" button

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU-Design-Editor#277]
## Technical
WATT
## Description
Chrome Zoom is 100% or more large, New Page Wizard can't see the "Accept", "Cancel" button.
So the user can't close the New Page wizard.

## Steps to reproduce
1. Create a new project in Design Editor
2. Enlarge Chrome Zoom value
3. Open the New Page Wizard 

## Expected behaviour
See the  "Accept", "Cancel" button
## Actual behaviour
Can't see the Accept", "Cancel" button

**Comment by korneliakobiela** [comment]
PR was merged. Please check if it works

**Comment by singa2000** [comment]
ok. It's good working. It can be closed
