### ISSUE TITLE
Wearable profile Button Style issue

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU-Design-Editor#278]
## Technical
WATT/VSCode
## Description
In the wearable profile,  when you select the Button Style to Circle button, it's not proper display.
Mobile profile is no problem, just wearable profile have the issue.

## Steps to reproduce
1. Create a new project in Design Editor
2. Create project by Wearable profile
3. Drag&Drop the button
4. Select the button -> Attirbute -> Style -> Circle button

## Expected behaviour
Good display
## Actual behaviour
It's not proper display

**Comment by wszczepanski97** [comment]
@singa2000,
As I observed, in wearable profile there is a problem for button with all of styles(right header button, left header button).
For wearable doesn't exist sth like "ui-btn-circle"(this class is added in mobile version) and there is no possibility to add a circle shape as a class. 
I talked to members of a team and I wonder if circle-shaped button is available in wearable profile or we should disable styles for button in wearable.

**Comment by wszczepanski97** [comment]
Sure, I am sorry for no response but I was on holiday.

**Comment by wszczepanski97** [comment]
PR #316 is merged. We can close an issue.

**Comment by singa2000** [comment]
It's good working .Thanks
