### ISSUE TITLE
The elements should be able to be deleted from the structure view

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU-Design-Editor#280]
## Technical
WATT/VSC
## Description
The elements should be able to be deleted from the structure view
## Steps to reproduce
1. Create a new project in Design Editor
2. Add the widget from Widget pannel
3. Select the "Structure Element Toggle" button in left toolbar
4. Open the structure view
5. Select the element and try to delete  in the structure view

## Expected behaviour
The elements are able to be deleted from the structure view.

## Actual behaviour
It can't delete from the structure view.

**Comment by lslachciak** [comment]
@singa2000 we are working on this issue as a part of https://github.com/Samsung/TAU-Design-Editor/issues/228
@korneliakobiela please confirm

**Comment by korneliakobiela** [comment]
The issue is merged, I can close this other one.

**Comment by singa2000** [comment]
In my test, it's not working.

1.Create a new project in Design Editor
2. Add the "Button" or "Checkbox" from Widget pannel
3. Select the "Structure Element Toggle" button in left toolbar
4. Open the structure view
5. Select the "button" or "checkbox" string in the structure view
6. In the keyboard, I push the "Delete" key
==> By "Delete" key in keyboard, it can't remove.

How did you delete it?

**Comment by singa2000** [comment]
I check it again, it's working.
But sometimes it's not working.
I'll more investigate how to reproduce it.
Now I think we can close the issue.
