### ISSUE TITLE
Selector widget is not displayed on the widget list for first load

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#281]
1. Create a new wearable project in Design Editor
2. Expand Containers list
Expected: Selector Widget is visible
Status: Selector widget is visible after clicking on the watch's background

**Comment by TomaszLukawskiSam** [comment]
The clue of issue is how Design Editor to set profile (mobile / wearable).

At start of the Design Editor a components panel is rendered eight times for different profiles and screen shapes.
![image](https://user-images.githubusercontent.com/29534410/63494085-4101a280-c4bd-11e9-9789-f33ab62866f4.png)

**Comment by lslachciak** [comment]
works fine
