### ISSUE TITLE
The Header text in the VSC can't display the font editor toolbar 

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU-Design-Editor#287]
## Technical
VSC

## Description
The Header text in the VSC can't display the font editor toolbar.
It was blocked in panel Info bar
 
## Steps to reproduce
1. Create a new project in Design Editor in VSC
2. Design Area Zoom is 100%
3. Double click the Header Text

## Expected behaviour
Display the  Font editor toolbar
## Actual behaviour
Can't be show the Font editor toolbar due to panel info bar

**Comment by wszczepanski97** [comment]
I can't reproduce this problem.
I check it on wearable and mobile and I don't see it.
Font editor toolbar displays on header the same as on span text.
@singa2000 please specify what project do you use and check is the problem exist.

**Comment by singa2000** [comment]
You can reproduce
Set : Mobile Profile Project -> Design Editor -> "Fit to screen" in below or Zoom set to 150% of design editor.
        Double click on the Header text.

**Comment by singa2000** [comment]
It can't  reproduce it.
We can close the issue
