### ISSUE TITLE
[VSC][Wearable] Input Text doesn't appear on template

### ISSUE THREAD

**Issue by wszczepanski97** [Samsung/TAU-Design-Editor#292]
## Technical
WATT, VSC
## Description
After d&d input text doesn't appear on template
## Steps to reproduce
1. Create a new project in Design Editor
2. D&D text input
## Expected behaviour
Text Input should appear 
## Actual behaviour
Text Input doesn't appear.

**Comment by korneliakobiela** [comment]
I think it can be TAU problem, but I am not sure

**Comment by lslachciak** [comment]
This issue also is for input password.
Interestingly it is not for input number

**Comment by lslachciak** [comment]
I think this issue is no longer valid,
I checked - input text appears correclty but is not editable in live preview
i'll create separate issue for this
@pkaczmarczy coul you confirm that this issue no longer exist?

**Comment by wszczepanski97** [comment]
Input text is visible on template, I close an issue.
