### ISSUE TITLE
[VSC][Wearable] Events added by JSAssistant don't work.

### ISSUE THREAD

**Issue by wszczepanski97** [Samsung/TAU-Design-Editor#293]
## Technical
VSC
## Description
Events such as go to the page doesn't work when added in JS assistant.
## Steps to reproduce
1. Create a new project in Design Editor
2. Add button to template.
3. Run JS assistant and set a variable for button.
4. Add event listener to button, select page transition to other page.
5. Click accept.
6. Launch preview mode and click on button.
## Expected behaviour
After click page should change.
## Actual behaviour
After click nothing happened

**Comment by korneliakobiela** [comment]
I cannot reproduce this issue. I am consulting it with @wszczepanski97 and decide to close the issue.
