### ISSUE TITLE
Duplicated display when drop the "text" and "image" widget

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU-Design-Editor#300]
## Technical
WATT/ VSCode

## Description
When the drop the "Text", "Image" widget into Template, it duplicated display .

## Steps to reproduce
1. Create a new project in Design Editor
2. Drag&Drop the "Text", "Image" widget

## Expected behaviour
Just once displayed

## Actual behaviour
Duplicated display 

I test by https://github.com/Samsung/TAU-Design-Editor/pull/284 and TAU library 1.1.3.
There was no problem by https://github.com/Samsung/TAU-Design-Editor/pull/285.

**Comment by singa2000** [comment]
@hsiwkin 
Can this issue be related to https://github.com/Samsung/TAU-Design-Editor/pull/284?

**Comment by hsiwkin** [comment]
I don't think so. #284 was "technical" PR that simplified code of guide.js but didn't affect the actual work of DE.

**Comment by singa2000** [comment]
It looks it just have the issue for text, image, video, audio widget.
It's not TAU component widget. 
It't for closet-component widget in the closet-component-packages\components.

**Comment by hsiwkin** [comment]
@singa2000 I've reviewed this issue once again and you were right - this error was connected with #284. The  PR: https://github.com/Samsung/TAU-Design-Editor/pull/308 should resolve it.

**Comment by singa2000** [comment]
@hsiwkin 
I test it in the VSC
After your PR, multiplication component issue was fixed.
But the image widget can not set the external image (The image is outside of Project).
Would you check it please?

P.S. I can't also be open the JavaScript Assistant, HTML Assistant view.
      How about you?
