### ISSUE TITLE
Wearable profile  "ui-content" height is too small, so I can't put the widget in empty area.

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU-Design-Editor#304]
## Technical
WATT/VSCode

## Description
Wearable profile empty page "ui-content" height is100px, and it's too small.
Mobile profile empty page is good working.

## Steps to reproduce
1. Create a new project in Design Editor by Wearable profle
2. New page -> Empty page or Header page -> Accept
3. Structure Element Toogle -> Select the "content"
4. Attribute -> Dimension -> Height is 100px

## Expected behaviour
We should be able to drag & drop the page anywhere.

## Actual behaviour
The content height is too small, so I can't drag&drop the widget  on the up and down area of  page

**Comment by pkaczmarczy** [comment]
The content is empty, and it's dimensions (and area that DE recognizes as content) it's defined by content padding styles.

ui-content element dimensions are defined by its children and document flow (Absolute positioned elements does not affect .ui-content dimmensions).
On mobile profile content is set by Page widget:
```
					if (!self.options.enablePageScroll) {
						contentStyle.height = (screenHeight - top - bottom) + "px";
					}
```

On wearable content is inside scrollview, on the other hand on mobile scroller is inside content.

**Comment by singa2000** [comment]
Would  you consider  HEADER page , Buttom page  etc besides  empty page,please?

**Comment by hsiwkin** [comment]
As far as I can see it's possible to add components to content in the empty page, footer & header page. 
As noted initial height of content is small but it is flexible and keeps resizing after being filled with components.

**Comment by lslachciak** [comment]
@singa2000 min-height is added both in examples as well as on new pages
