### ISSUE TITLE
Behavior-> Events -> animation don't work

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU-Design-Editor#305]
## Technical
WATT / VSCode

## Description
Behavior-> Events -> animation don't work

## Steps to reproduce
1. Create a new project in Design Editor
2. Drag&Drop the widget and select
3. Behavior -> Event -> do: animation select

## Expected behaviour
Can select the "Choose File"

## Actual behaviour
Can't select the "Choose File"

**Comment by korneliakobiela** [comment]
I close this issue because its working
