### ISSUE TITLE
Preview element is moved to top of screen

### ISSUE THREAD

**Issue by korneliakobiela** [Samsung/TAU-Design-Editor#319]
## Technical
Platform: WATT
code.tizen.org
Demo mode
## Description
When user open example in demo mode, then preview element is moved to the top of screen and then only bottom half of application is visible
## Steps to reproduce
1. Go to the page http://localhost:3000/demos?path=1.0%2Fexamples%2Fmobile%2FUIComponents%2Fcomponents%2Fnavigationelements%2Fpanel%2Findex.html
2. Open the preview

## Expected behaviour
Preview of the app in the centre of screen.
## Actual behaviour
Preview of the app on the top of the screen.

**Comment by lslachciak** [comment]
This is regression because of one of patches between 0.6.6 and 0.6.7

**Comment by korneliakobiela** [comment]
Ok, I've found the commit which spoils it. This was 
> 6a4b320 Preview mode appears always in the centre of the screen
I will investigate it

**Comment by singa2000** [comment]
Is it also reproduce in the https://developer.tizen.org/development/api-references/web-application?redirect=https://developer.tizen.org/dev-guide/5.0.0/org.tizen.web.apireference/html/ui_fw_api/Mobile_UIComponents/mobile_Navigation.htm -> Use Example?

**Comment by korneliakobiela** [comment]
Ok, the easiest way to fix it, is reverting commit listed above. I suppose that the issue is more serious than it looks like. It occurs only in the first preview opening. I think there can be some issue with less, because we use some old version of it, but I can be wrong. Due to more priority issue I switch to another one.

**Comment by grzegorz-czajkowski** [comment]
I am able to reproduce this, having WATT and updated DE submodule. What's is interesting this issue does not happen for regular samples (embedded in WATT). Only samples opened via demos API are broken. Will start to investigate this.

**Comment by lslachciak** [comment]
@singa2000 we need to fix this issue, without it we are blocked with any updates of DE in WATT
(so it relfects also code.tizen.org)

**Comment by grzegorz-czajkowski** [comment]
The cause of this issue is **closet-design-editor-frame** visibility set to **hidden**. This is done on purpose for remote samples in order not to show design editor mode and to go preview directly.

Because of  closet-design-editor-frame visibility hidden, **getBoundingClientRect**() returns 0 which results in not removing **transform: translate(-50%, -50%)** in preview-element.js::setProfileStyle().

I am in the middle of fixing this based on above investigations. Then I will need to test it on both WATT and VSC.

**Comment by korneliakobiela** [comment]
Now it looks good both in WATT and VSC.
