### ISSUE TITLE
[VSCode] Too long header description hides additional panels

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#322]
## Technical
 [VSCode] Too long header description hides additional panels

## Steps to reproduce
1.Open a new project in Design Editor
1.Run Structure Element Toggle Code
2.Run JS Assistant Wizard

## Expected behaviour
Both panels visible
## Actual behaviour
Only one panel is visible
![image](https://user-images.githubusercontent.com/2246331/64252678-e3893f00-cf1b-11e9-82e3-e99f0b02a61d.png)

**Comment by korneliakobiela** [comment]
This is not entirely an issue, rather a functionality. When open JS Assistant the area for Design Editor is much smaller, so all the right menus(attributes. widgets, behaviours, and structure view) are not displayed. The only issue I can see is that the button of this is enabled.

**Comment by lslachciak** [comment]
Issue depends on the item description. We should consider disabling Structure element when JS assistant visible an vice versa

**Comment by lslachciak** [comment]
This issue is also visible when coverflow widget used and few fiels selected  Attributes tab is not visible
![image](https://user-images.githubusercontent.com/2246331/64600153-efad4a80-d3ba-11e9-8ae6-1b944c1c22a6.png)

I think we should shorten header description in order to allow see content on the right side

**Comment by wszczepanski97** [comment]
The problem exists in WATT also but is less visible because window with js/html assistant by default is smaller than in VSCode.

**Comment by singa2000** [comment]
The patch is merged and it's good working.
Thanks
