### ISSUE TITLE
[VSCode] Unable to move widgets

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#323]
## Technical
[VSCode] Unable to move widgets:
- Input Text"
- Progress
- Input number

## Steps to reproduce
1. Open empty mobile  project in Design Editor
2. Place Input text widget
3. Try to move it.

## Expected behaviour
Element is moved

## Actual behaviour
No movement occurs
[Mobile TAU Sample App.zip](https://github.com/Samsung/TAU-Design-Editor/files/3574443/Mobile.TAU.Sample.App.zip)

![image](https://user-images.githubusercontent.com/2246331/64253529-c8b7ca00-cf1d-11e9-85ca-706ebab4c2ba.png)

**Comment by lslachciak** [comment]
Also I'm not able to move progrees widet in case of wariable

**Comment by lslachciak** [comment]
@wszczepanski97 PR merged, can we send this issue to review?

**Comment by wszczepanski97** [comment]
Yes, I am sorry we can review this issue.
Please check is this patch works on wearable too, it should.

**Comment by lslachciak** [comment]
I'm able to move widgets on mobile but in case of wearable progress widget is not movable

**Comment by lslachciak** [comment]
![image](https://user-images.githubusercontent.com/2246331/64601064-89292c00-d3bc-11e9-824d-4e09f12ee983.png)

**Comment by wszczepanski97** [comment]
Progress is draggable on wearable too, patch is merged.
@lslachciak, we can close an issue.

**Comment by lslachciak** [comment]
works great, thank you
