### ISSUE TITLE
Changing progress background color has issues

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#325]
## Technical
Changing progress background color has issues

## Steps to reproduce
1. Open a project in Design Editor
2. D&D Progress widget
3. Click widget and open Attributes tab
4. Change background color

## Expected behavior
Both in Editing and Live Preview mode progress has proper bacgkround or background color change is disabled for this element.

## Actual behavior
Changing color has strange effect in Editing mode and no effect in Live Preview mode.

![image](https://user-images.githubusercontent.com/2246331/64256177-30244880-cf23-11e9-87e7-f5cfd668fe06.png)

**Comment by korneliakobiela** [comment]
The styling progress element is not as easy as other HTML elements. It behaves strangely in different browsers even in versions of the same one. Article about it you can read here: https://css-tricks.com/html5-progress-element/

I think there is some other problem (not sure if in DE or TAU). The design of the progress bar looks like it could be the standard browser styling, not a TAU one. 

Here is graphic what progress should look:
![image](https://user-images.githubusercontent.com/18300603/64430125-def98d80-d0b7-11e9-827d-15d194365aeb.png)
And here is some example of the standard progress bar https://jsfiddle.net/1r3b4gmp/3/

**Comment by korneliakobiela** [comment]
That's a strange situation. Progress Element existing in Design Editor is built from native HTML progress element and it doesn't work at all. On the other hand in Tau UI-Components there are several examples of working progress both bar and circle. However, if I change the DE template of Progress Component, to make it similar to UI-Components one. It partially works but from some reason isn't draggable.

**Comment by korneliakobiela** [comment]
The patch is merged. Please, review it.

**Comment by lslachciak** [comment]
Yes, now we can cenge progress background but we need to deal with below ones with 

https://github.com/Samsung/TAU-Design-Editor/issues/370
https://github.com/Samsung/TAU-Design-Editor/issues/368
https://github.com/Samsung/TAU-Design-Editor/issues/369

Especially issue #368 is a must
