### ISSUE TITLE
Add section button is hard to see

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#326]
## Technical
Add section button is hard to see
![image](https://user-images.githubusercontent.com/2246331/64263104-6962b580-cf2f-11e9-8885-c28bf6537641.png)
In order to see  button you need to click section changer and move mouse into area of arrows.
Button should be visible immediately
## Steps to reproduce
1.Drag&Drop Section Changer widget

2. Select Section Changer widget and click + button few times in order to add sections to page
## Expected behaviour
+ button is easil visible
## Actual behaviour
hard to see + button

**Comment by grzegorz-czajkowski** [comment]
Section changer add buttons are hidden. To make them visible user must hover on them.  
I changed this by showing add buttons if section changer is active.

To make the feature more user friendly, we should activate section changer after drag&drop. Now it must be clicked to be active.

**Comment by lslachciak** [comment]
works well
