### ISSUE TITLE
Slider changes its height on focus

### ISSUE THREAD

**Issue by hsiwkin** [Samsung/TAU-Design-Editor#331]
## Technical
Platform: Both
## Description
Slider component changes its height after being dragged and clicked.
## Steps to reproduce
1. Create a new project in Design Editor
2. Drag & drop slider
3. Move it
4. Click on the page (outside of the slider)
5. Click on slider
## Expected behavior
The slider is selected and without changing its looks 
## Actual behavior
The slider is selected but its view is broken (its resized vertically)

**Comment by hsiwkin** [comment]
PR #337 will resolve this issue.

**Comment by lslachciak** [comment]
Waiting for PR #337 to be merged

**Comment by hsiwkin** [comment]
I've just merged the PR #337

**Comment by lslachciak** [comment]
works good, thank you
