### ISSUE TITLE
[VSCode] Coverflow widget - unable to select

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#334]
## Technical
[VSCode] Coverflow widget - unable to select

## Steps to reproduce
1. Open Sample project in Design Editor
2. D&D Coverflow widget
3. Try to select it

## Expected behaviour
Coverflow widget is selected
## Actual behaviour
Not able to select Coverflow widget

**Comment by korneliakobiela** [comment]
The problem occurs because the coverflow widget doesn't have its height when empty. I can fix it to add some standard height param. Are you ok with this solution?

**Comment by singa2000** [comment]
As  I  known  Mr.Lim  fixed the  issue  and  reviewing.

**Comment by lslachciak** [comment]
@DohyungLim could you cinfirm and take over this issue?

**Comment by korneliakobiela** [comment]
Sorry, I didn't notice that. This issue wasn't assigned to anybody

**Comment by lslachciak** [comment]
same issue fo wearable profile

**Comment by DohyungLim** [comment]
https://github.com/Samsung/TAU/pull/364

The patch has merged. You can check the coverflow even in the wearable when you apply a new TAU.

**Comment by lslachciak** [comment]
No we can select coverflow widget, but selected files are not stored. I will report separate issue
