### ISSUE TITLE
Interactive 3D model  no models

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#335]
## Steps to reproduce
1. .Drag&drop "Interactive 3D Model" widget on the project template
2. Set the Interactive model
3.Select the Preview

## Expected behaviour
You can see the Interactive 3D model
## Actual behavior
No models to select available

![image](https://user-images.githubusercontent.com/2246331/64419131-836dd680-d09c-11e9-8689-301a478cef5d.png)

**Comment by lslachciak** [comment]
@singa2000 this issue still exist PR https://github.com/Samsung/TAU-Design-Editor/pull/352 is not merged yet

**Comment by singa2000** [comment]
The PR was merged and good working.
It can be closed.
