### ISSUE TITLE
[VSCode] [Wearable] Image widget has strange image src set by default

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#339]
## Technical
[VSCode] [Wearable] Image widget has strange image src set by default

## Steps to reproduce
[W Sample TAU 1.1.4.zip](https://github.com/Samsung/TAU-Design-Editor/files/3590275/W.Sample.TAU.1.1.4.zip)
1. open attached sample project in DE
2. D&D image widget 
3. Go to Attributes->Image-->SRC
## Expected behaviour
Nothing is set in src
## Actual behaviour
Strange "# is set as a source
![image](https://user-images.githubusercontent.com/2246331/64528228-3beb8280-d308-11e9-9602-51c39855f1d8.png)

**Comment by wszczepanski97** [comment]
PR is merged, @lslachciak please check is patch works.

**Comment by lslachciak** [comment]
works fine, thank you
