### ISSUE TITLE
Toggle switch has improper look

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#341]
## Technical
Toggle switch has improper look  for wearable

## Steps to reproduce
1. Open a project in Design Editor (VSCode)
2. D&D toggle switch

## Expected behaviour
toogle siwtch is visible

## Actual behaviour
checkbox like widget is visible
![image](https://user-images.githubusercontent.com/2246331/64529690-b4a00e00-d30b-11e9-8f5a-70c961b27571.png)

**Comment by hsiwkin** [comment]
PR https://github.com/Samsung/TAU-Design-Editor/pull/374/files should fix this issue

**Comment by hsiwkin** [comment]
I've stopped working on this case to take care of #347 and #304 which have a higher priority at this moment.

**Comment by hsiwkin** [comment]
I've removed the old component and created 2 new ones for Toggle Switch (one for wearable and one for mobile). 
They have different templates.  The components looks properly in preview mode:
![localhost_3000_brackets_5d947c3d28d20b5697851be2 (1)](https://user-images.githubusercontent.com/6040157/66147675-9a5a0700-e60f-11e9-81e6-6e106e5431b0.png)
![localhost_3000_brackets_5d961f1f485ca056d923c8c6](https://user-images.githubusercontent.com/6040157/66147689-a3e36f00-e60f-11e9-8f57-d4f5f35cc10b.png)
but there is some overflow in wearable in edit mode:
![localhost_3000_brackets_5d947c3d28d20b5697851be2](https://user-images.githubusercontent.com/6040157/66147723-b362b800-e60f-11e9-9cca-f7dab7047891.png)

**Comment by hsiwkin** [comment]
All changes are in PR: https://github.com/Samsung/TAU-Design-Editor/pull/374
