### ISSUE TITLE
(Wearable) Unable to put password on Input Password

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#344]
(Wearable) Unable to put password on Input Password

![image](https://user-images.githubusercontent.com/2246331/64530484-8f140400-d30d-11e9-982f-e6db95c78504.png)

**Comment by lslachciak** [comment]
Also there is no possibility to put text on input text

**Comment by korneliakobiela** [comment]
I am looking for a reason for this issue. I can see it properly in TAU UI-Components demo and I will look for some differences in packages, dependencies, versions etc.

**Comment by korneliakobiela** [comment]
I've fixed it. It was issue with tau.circle.css appended twice. One from the template (as tau.circle.min.css) and second added by the editor.

**Comment by korneliakobiela** [comment]
The issue was merged, please review it and test if other issues weren't solved by this one

**Comment by lslachciak** [comment]
works fins, thank you
