### ISSUE TITLE
TAU popup is not opened in Live Preview

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#345]
## Technical
1. open Wearable or Mobile project in DE
2. D&D Button
3. Open JS Assistant
4. Click Button
5. Click Insert Code
6. Event Listener > Click Popup Open
7. go Live Preview
8. Click button

## Expected behaviour
Popup is oopened
## Actual behaviour
No popup open

**Comment by korneliakobiela** [comment]
Did you added any pop-up to the project into Design Editor?

**Comment by lslachciak** [comment]
According to the doc
https://docs.stg.tizen.org/application/web/api/5.0/ui_fw_api/Base/popup.htm

tau.openPopup(to) 
Opens a popup by calling the openPopup() method. The to argument is a pop-up container object **or string.**

so we need to clarify if string is enough or not.

But tried also with object without success.

**Comment by singa2000** [comment]
@lslachciak 
I test in latest TAU Design Editor, it looks working.
I think , we need to append POP-UP component first.
How about your think?

**Comment by lslachciak** [comment]
it is ok, but tizen documentation should be updated for tau.openPopup(to)
it is not true that 
**argument is a** pop-up container object or **string.**
string text can not be an argument, only popup id
I'll update doc

**Comment by lslachciak** [comment]
PR merged, closing issue
