### ISSUE TITLE
unable to place dimmer widget properly on wearable sample app

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#347]
## Technical
unable to place dimmer widget properly on wearable sample app
## Steps to reproduce
1. Open sample project in DE
2. D&D dimmer widget
3. Tr to place it full screen

## Expected behaviour
Widget can be placed for full screen or small circle
## Actual behaviour
![image](https://user-images.githubusercontent.com/2246331/64533588-12385880-d314-11e9-94af-443fa304303d.png)

**Comment by singa2000** [comment]
@lslachciak 
It looks important issue with https://github.com/Samsung/TAU-Design-Editor/issues/304.
In the wearable profile, I try to add some widget besides dimmer, there display the scrollbar and unable to place proper position.
Before release, would you fix it , please?

**Comment by lslachciak** [comment]
OK, we will take care of it with pripority

**Comment by singa2000** [comment]
index.html or empty.html in the wearable profile
->put the Dimmer or Graph
-> Drag for resize 
=> Scroll is generated horizontally and vertically.
: It have to put normally position without the scrollbar

**Comment by lslachciak** [comment]
[W Sample TAU 1.1.4.zip](https://github.com/Samsung/TAU-Design-Editor/files/3645803/W.Sample.TAU.1.1.4.zip)

**Comment by lslachciak** [comment]
After placing graph on new empty page:
![image](https://user-images.githubusercontent.com/2246331/65491275-05d50380-deaf-11e9-9581-7b905d20e1cc.png)

After moving graph widget a little bit
![image](https://user-images.githubusercontent.com/2246331/65491298-0ff70200-deaf-11e9-910b-1aa2a3908a88.png)
(can't get rid scrollbars after)

**Comment by lslachciak** [comment]
After removing **style="position: relative;"** from 
<div class="ui-content" style="position: relative;">
scrollbars disappear

**Comment by lslachciak** [comment]
discussed issue with @hsiwkin who will continue issue
one of option is to consider is to resize content widget as a quick fix
