### ISSUE TITLE
[wearable] [VSCode] Progress widget is not visible in DE live preview

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#351]
[wearable] [VSCode] Progress widget is not visible in DE live preview

![image](https://user-images.githubusercontent.com/2246331/64620753-c0abce80-d3e4-11e9-8d08-e350460c4b9f.png)

![image](https://user-images.githubusercontent.com/2246331/64620714-b093ef00-d3e4-11e9-8706-11cbdb70a8d9.png)

**Comment by hsiwkin** [comment]
PR #366 resolves this issue.

**Comment by lslachciak** [comment]
works fine
