### ISSUE TITLE
[Mobile] Coverflow - selected files not saved in object properties

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#359]
[Mobile] Coverflow widget  - selected files not saved in object properties

Prereq:
Use TAU 1.1.4 sample (attached)
Latest VSCode DE

1. Add coverflow widget
2. Attributes->Coverflow-->Files Selection-->Choose files
3. Select some img files
4. Click outside of coverflow widget
5. Click on coverflow widget again
Oberve:
no files seleted
Expected:
Previously selected files visible

**Comment by wszczepanski97** [comment]
PR #413 is merged.
Please check is coverflow working.
