### ISSUE TITLE
Audio/Vieo Components loses value when focus and then click it one more time

### ISSUE THREAD

**Issue by wszczepanski97** [Samsung/TAU-Design-Editor#365]
## Technical
VSCode&&WATT
## Description
After choosing file for Audio Component, it holds value correctly.
If it loses focus, value disappears and "No file chosen" string is displayed.
## Steps to reproduce
1. Create a new project in Design Editor
2. D&D audio component
3. Choose a file in Element bar for audio component.
4. Set focus on sth else(another widget added to template etc.)
5. Click on Element Bar
## Expected behaviour
Next to Choose File input should be name of added file
## Actual behaviour
![noFileChosen](https://user-images.githubusercontent.com/31214439/65150643-dd6b8600-da24-11e9-885c-25b75a63b9f6.png)

"No File Chosen" string is displayed.

**Comment by wszczepanski97** [comment]
Video Component has the same problem.

**Comment by lslachciak** [comment]
similar situation with coverflow widget

**Comment by wszczepanski97** [comment]
PR #389 is merged.
I close an issue
