### ISSUE TITLE
[DE] Can't resize Section Changer

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#380]
Section changer should be resizable.
There is a need to resize it in some cases

![image](https://user-images.githubusercontent.com/2246331/65511136-cc17f300-ded6-11e9-851f-07b6512774c1.png)

**Comment by grzegorz-czajkowski** [comment]
This issue is fixed by https://github.com/Samsung/TAU-Design-Editor/pull/385

**Comment by lslachciak** [comment]
PR#385 is not enough, we need more fix here

**Comment by grzegorz-czajkowski** [comment]
Resizing **SectionChanger** is possible after #385. However, once resize is done and user clicks on **Section** then **SectionChanger** height is changed, usually to 395px but **Section** is not resized at all. What's more, second click on **Section** changes  **SectionChanger** height  to Section height (585). I am looking for script that changes it.

**Comment by grzegorz-czajkowski** [comment]
On section changer resize end, **refresh** method on TAU widget is called which resets **height** of sections in **_initLayou**t:

```
            _initLayout: function() {
                var a, b, c, d = 0, f = 0;
                for (b = 0,
                c = this.sections.length; c > b; b++)
                    a = this.sections[b].style,
                    a.position = "absolute",
                    this.options.fillContent && (a.width = this._sectionChangerWidth + "px",
                    a.height = this._sectionChangerHeight + "px"),
```
this._sectionChangerHeight seems to have container (scroller) height not current size from resize.

**Comment by grzegorz-czajkowski** [comment]
I have working patch for Mobile profile. Wearable profile does not fully work since _containerExpander::rollOut()_  function determines new height for section changer.

**Comment by grzegorz-czajkowski** [comment]
Patch to TAU 1.0 has been merged.
To have this change in WATT there is a need:
 - enable sectionchanger widget in DE,
 - push patch to TAU 1.1.
 - update submodule TAU 1.1 in WATT
