### ISSUE TITLE
Can't add widgets to section

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#381]
1. Add Mobile Sample project
2. Add Section Changer with Seciton
3. D&D Graph/Input*/Progress/Audio/Video/Dimmer  widget
Observe: not able to add it.

![image](https://user-images.githubusercontent.com/2246331/65511954-9d9b1780-ded8-11e9-9f6b-072d701612aa.png)

**Comment by singa2000** [comment]
PR is ready : https://github.com/Samsung/TAU-Design-Editor/pull/385

**Comment by singa2000** [comment]
PR is merged.
