### ISSUE TITLE
Coverflow widget does not work in live preview of wearable profiles

### ISSUE THREAD

**Issue by DohyungLim** [Samsung/TAU-Design-Editor#386]
## Steps to reproduce
1. Create a new project in Design Editor **(wearable TAU Basic sample and TAU 1.1.4 version)**
2. Added coverflow widget.
3. Add a file and select Effect.
4. Run Preview.

## Expected behaviour
The effect is applied to the coverflow widget.

## Actual behaviour
The coverflow widget looks like a list. (No effect applied.)

## PS
In my guess, the problem occurs in tau.bundle.js.
I compared the 2 cases.
//origin code only 1 line added.
//<script src="lib/tau/wearable/js/tau.bundle.js"></script>

1. Use tau.js and declare external library files separately.
<script src="lib/tau/wearable/js/jquery.min.js"></script>
<script src="lib/tau/libs/jquery.flipster.min.js"></script>
<script src="lib/tau/wearable/js/tau.js"></script>
-> If you modify the code like this, the wearable profile will work normally in live preview

2. Declare an external library file and tau.bundle.js.
<script src="lib/tau/wearable/js/jquery.min.js"></script>
<script src="lib/tau/libs/jquery.flipster.min.js"></script>
<script src="lib/tau/wearable/js/tau.bundle.js"></script>
-> If you modify the code like this, it will not work.

**Comment by lslachciak** [comment]
@DohyungLim I assume that for this issue 1.1.4 TAU example was used like this one

**Comment by DohyungLim** [comment]
@lslachciak 
That's right. The problem occurs in version 1.1.4. I'll fill in additional details.

**Comment by pkaczmarczy** [comment]
I am checking the issue. I have run TAU UIComponents app (from TAU repo) and it looks correct there.

With the latest bundled build page with coverflow requires only `tau.js` adequate to the profile and `tau.coverflow.js` file which already includes jQuery and flipster sources.

I have run this page in Chrome browser and coverflow widget looks correct.
```
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width,user-scalable=no"/>
	<link rel="stylesheet" href="../../../lib/tau/wearable/theme/default/tau.css">
	<link rel="stylesheet" href="../../../lib/tau/wearable/theme/default/tau.circle.css">
	<script type="text/javascript" src="../../../lib/tau/wearable/js/tau.js" data-build-remove="false"></script>
</head>
<body>
<div class="ui-page" id="demo-page">
	<script type="text/javascript" src="../../../lib/tau/libs/tau.coverflow.js"></script>
	<div class="ui-header" data-position="fixed">
		<h1>CoverFlow</h1>
	</div>
...
```

And I get:
![Screenshot from 2019-09-25 11-44-23](https://user-images.githubusercontent.com/38784474/65589764-e1018e80-df89-11e9-907e-b29ecfe7604c.png)

However, the attached sample does not contain correct TAU 1.1.4 version.
content of lib/tau/libs directory should be different and it should only contain:
```
tau.graph.js
tau.coverflow.js
tau.i3d.js
```
I will check how the app is working in DE with those files.

**Comment by DohyungLim** [comment]
@pkaczmarczy 
There is an entry to add the Coverflow widget to Design-Editor validation.
Will it work in Preview in DE?
I use tau.bundle.js. (The verification sample uses tau.bundle.js.)

**Comment by lslachciak** [comment]
https://github.com/Samsung/TAU-Design-Editor/files/3651414/W.Sample.TAU.1.1.4.zip was generated using WATT (New -> Sample Project) and is not containg latest TAU bundle related changes

**Comment by lslachciak** [comment]
[M Sample Tau 1.1.4.zip](https://github.com/Samsung/TAU-Design-Editor/files/3651981/M.Sample.Tau.1.1.4.zip)

**Comment by pkaczmarczy** [comment]
OK, there was a problem with a 1.1.4 release, not all of the files were included correctly.

I have updated the sample with provided by @lslachciak with tau 1.1.5.
I also added the tau.graph.js, tau.coverflow.js, tau.i3d.js in advance due to DesignEditor external resources loading problem (https://github.com/Samsung/TAU-Design-Editor/issues/247). 

I was able to show the Coverflow widget correctly (I have modified the html source rather than use image imports by DE), which means that all resources have been loaded successfully. 

![Screenshot from 2019-09-25 12-54-58](https://user-images.githubusercontent.com/38784474/65595254-a3563300-df94-11e9-8369-a04d0b2a22a2.png)

Updated wearable sample:
[W_Sample_TAU_1.1.5.zip](https://github.com/Samsung/TAU-Design-Editor/files/3652041/W_Sample_TAU_1.1.5.zip)

**Comment by pkaczmarczy** [comment]
Mobile coverflow verification (done by changin HTML sources), coverflow resources are loaded correctly:
![Screenshot from 2019-09-25 13-14-29](https://user-images.githubusercontent.com/38784474/65596160-99cdca80-df96-11e9-8cd8-e9f21ec9a90b.png)

**Comment by lslachciak** [comment]
I verified also provided 1.1.5 sample and coverflow widget works properly on wearable live preview except small issue reported here: https://github.com/Samsung/TAU-Design-Editor/issues/387

**Comment by DohyungLim** [comment]
I've built and applied the fix from TAU.
All results after applying the patch will work normally.
Please apply the patch below. I will close the issue.

https://github.com/Samsung/TAU/pull/407
