### ISSUE TITLE
(minor) Coverflow widget doesn't have default Effect Selection

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#387]
1. Open 1.1.5 Wearable sample
2. Add Coverflow widget
3. Coverflow->File Selection--> ads some files
4. Run Live Preview
Expected:
Coverflow effect is visible for selected images
Observe:
![image](https://user-images.githubusercontent.com/2246331/65598317-6e011380-df9b-11e9-9a70-46907f6f639c.png)
Note: After choosing Effect Selection coverflow widget is displayed properly
![image](https://user-images.githubusercontent.com/2246331/65598433-ad2f6480-df9b-11e9-83bb-c318f6e0a6b6.png)

**Comment by wszczepanski97** [comment]
I need to resolve this issue first before I start work with #387

**Comment by wszczepanski97** [comment]
I think that we can close this issue.
@lslachciak please check is coverflow build by default.

**Comment by lslachciak** [comment]
works well, thank you
