### ISSUE TITLE
Can not add TAU widgets to new page when using TAU 1.1.5 sample

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#388]
1. Use [W_Sample_TAU_1.1.5.zip](https://github.com/Samsung/TAU-Design-Editor/files/3652442/W_Sample_TAU_1.1.5.zip)
2. Run DE
3. Click add New Page
4. Observe:
Not able to add any TAU  widget

**Comment by lslachciak** [comment]
This is due to the missing tau-bundle in 1.1.5

**Comment by pkaczmarczy** [comment]
Verification in progress.

I have checked mobile profile samples with fresh tau.bundle file only included - It looks like they are OK

**Comment by lslachciak** [comment]
I added PR which will eliminate issue with 1.1.5 samples
Separately I wish to
- update WATT samples + TAU to version 1.1.5
- update DE to disable some widgets if additional libraries not included

**Comment by lslachciak** [comment]
PR https://github.com/Samsung/TAU-Design-Editor/pull/393 merged
Also samples for TC updated http://suprem.sec.samsung.net/confluence/display/CBEFLC/Test+Case+of+VS+Code+Extension+for+Design+Editor
PR for WATT in review

**Comment by lslachciak** [comment]
Both PR for WATT and DE merged
