### ISSUE TITLE
Enable SectionChanger

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#398]
Component was disabled in 
https://github.com/Samsung/TAU-Design-Editor/pull/372

**Comment by grzegorz-czajkowski** [comment]
Bug fixes related with section changer:
 - https://github.com/Samsung/WATT/pull/187
 - https://github.com/Samsung/TAU-Design-Editor/pull/412
 - https://github.com/Samsung/TAU/pull/423

Once all of them are merged I restore SectionChanger in WATT.

**Comment by grzegorz-czajkowski** [comment]
Out of scope.
