### ISSUE TITLE
Section Changer - deleting sections issue

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#415]
## Steps to reproduce
1. Use https://github.com/Samsung/TAU-Design-Editor/pull/414
2. Create a new project in Design Editor in WATT
Sample --> Mobile --> TAU Basic
3. D&D Section Changer widget
4. Click + sign to ad section
5. Press delete button
## Expected behavior
One section is removed but section changer is still visible
OR
whole section changer is removed
## Actual behavior
one section is removed but section changer is no longer visible

![image](https://user-images.githubusercontent.com/2246331/66461512-7bc59700-ea79-11e9-94e6-d4794ef68c07.png)

**Comment by grzegorz-czajkowski** [comment]
Able to reproduce it.
I prefer removing a particular section (currently visible) to removing whole section changer. 
If there is only section, we should remove whole section changer.

**Comment by grzegorz-czajkowski** [comment]
Out of scope.
