### ISSUE TITLE
User cannot set predefined styles to element

### ISSUE THREAD

**Issue by korneliakobiela** [Samsung/TAU-Design-Editor#416]
## Technical
WATT/VSCode
Mobile

## Description
Nothing happened when user clicks on styles of an element.
## Steps to reproduce
1. Create a new project in Design Editor
2. Add listview or button
3. Select it
4. Click styles label on attributes

## Expected behaviour
The selected element is changing its styles.
## Actual behaviour
Nothing happened.

**Comment by hsiwkin** [comment]
https://github.com/Samsung/TAU-Design-Editor/pull/419 fixes this commit

**Comment by korneliakobiela** [comment]
Done and works!
