### ISSUE TITLE
[Mobile] [Coverflow] [LivePreview] widget not working properly

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#435]
Visit: https://code.tizen.org/demos?path=1.1%2Fexamples%2Fmobile%2FUIComponents%2Fcomponents%2Finteractive%2Fcoverflow%2Findex.html
Click: LivePreview icon
Observe: 
- not able to slide coverflow widget with mouse
- when using mouse scroller coverflow widget is "bumping"
Expected:
coverflow widget working with mous OR scroller

**Comment by DohyungLim** [comment]
@lslachciak 
class="coverflow-image" does not exist in the current sample.
class exists in the following locations in the original: TAU/examples/UIComponents/css/style.css
for the content of the class, simply enter width and height as 100px.
style="width: 100px; height: 100px;"

change the class in the link above to style.
or include the style.css file in the link.

**Comment by DohyungLim** [comment]
@TomaszLukawskiSam @lslachciak 
https://github.com/Samsung/TAU/pull/485
I have upload patch. please check review.
