### ISSUE TITLE
[Mobile] [Interactive3d] [LivePreview] widget not working properly

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#437]
visit: https://code.tizen.org/demos?path=1.1%2Fexamples%2Fmobile%2FUIComponents%2Fcomponents%2Finteractive%2Finteractive3D%2Findex.html
click LivePreview icon
Observe:
![image](https://user-images.githubusercontent.com/2246331/68945358-84b03380-07b0-11ea-92f1-98f81339693c.png)
Console:

```
(unknown) Uncaught TypeError: t is not a function
    at Object.eval [as onError] (eval at t.exports (tau.i3d.js:1), <anonymous>:14:74308)
    at XMLHttpRequest.eval (eval at t.exports (tau.i3d.js:1), <anonymous>:2:399832)
eval
eval
load (async)
load
load
load
play
attributeChangedCallback
g.attributeChangedCallback
eval
prototype._build @ tau.js:28446
prototype.build @ tau.js:5653
coreProcessWidget @ tau.js:3251
processWidget @ tau.js:3311
processHollowWidget @ tau.js:3428
processBuildQueueItem @ tau.js:3465
createWidgets @ tau.js:3521
prototype.change @ tau.js:14615
routePage.open @ tau.js:53065
resolve @ tau.js:15468
Router._openDeferred @ tau.js:15482
Router.open @ tau.js:15537
Router.register @ tau.js:15877
Router.init @ tau.js:15653
(anonymous) @ tau.js:16318
trigger @ tau.js:1545
build @ tau.js:3585
(anonymous) @ tau.js:1869
(unknown) Uncaught TypeError: t is not a function
    at Object.eval [as onError] (eval at t.exports (tau.i3d.js:1), <anonymous>:14:74308)
    at XMLHttpRequest.eval (eval at t.exports (tau.i3d.js:1), <anonymous>:2:399832
```

**Comment by lslachciak** [comment]
I think problem is because wget can not download interactive3d example

**Comment by lslachciak** [comment]
<div class="ui-content">
		<div class="ui-i3d"
			width="320"
			height="240"
			position="0 0 0"
			scale="50 50 50"
			rotation="0 -90 0"
			light="0xbbbbbb 0x000000 2"
			controls
			autoplay
			src="assets/Duck.gltf">
		</div>
	</div>

**Comment by lslachciak** [comment]
We should check follow-tags option

https://superuser.com/questions/988289/wget-parsing-tag-script

**Comment by lslachciak** [comment]
we can not use follow-tags option because wget is not recognising <div> tag with attribute <src> what is out of specification
we can use
<link href="">
in order to reference resource and make wget downloading them, but still for unknown reason i3D widget has issue.
Under investigation

**Comment by singa2000** [comment]
/UIComponents/contents/interactive/interactive3D/assets/Duck.gltf
/UIComponents/contents/interactive/interactive3D/assets/Duck0.bin
/UIComponents/contents/interactive/interactive3D/assets/DuckCM.png
files are needed but now it's missing.

**Comment by lslachciak** [comment]
@singa2000 right, this is core issue.
The problem is that wgte is not downloading those resource. That is why I made a trick in order to force wget downloading them. Check PR.

**Comment by lslachciak** [comment]
fixed
