### ISSUE TITLE
[Wearable] [Coverflow] [LivePreview] widget not working properly

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#438]
visit: https://code.tizen.org/demos?path=1.1%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Finteractive%2Fcoverflow%2Findex.html
click: LivePreview
Observe:
![image](https://user-images.githubusercontent.com/2246331/68945648-26d01b80-07b1-11ea-89dc-950472c88228.png)
Expected: full title visible

**Comment by DohyungLim** [comment]
@lslachciak 
That's weird. I do not remember modifying the title in coverflow.
My guess is that the title role will conflict depending on the TAU version?
I simply test adding a style to the h1 tag on line 22.
"< h1 style="text-align: center;">CoverFlow< /h1>"
The title is normally visible in the center without any problems.
But there is a way to fix this, but when I added coverflow earlier, the title was ok.

Look for differences in titles or headers depending on the version.

**Comment by DohyungLim** [comment]
@lslachciak 
code should apply to css.
< link rel="stylesheet" href="../../../lib/tau.circle.css" >

**Comment by DohyungLim** [comment]
@TomaszLukawskiSam @lslachciak 
https://github.com/Samsung/TAU/pull/485
I have upload patch. please check review.
