### ISSUE TITLE
[Wearable] [Coverflow] [LivePreview] widget scrolls up

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#442]
1. visit: https://localhost:3000/demos?path=1.1%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Finteractive%2Fcoverflow%2Findex.html
2. go to live preview
3. scroll content with mouse scroller
observe:
widget moves up
expected:
no widget move

**Comment by DohyungLim** [comment]
@lslachciak 
Could you please give me a link to the code.tizen.org issue so I can test it?

**Comment by DohyungLim** [comment]
Did you move the scroll in a non-image area when testing? Scrolling and clicking do not work in non-image areas.

**Comment by lslachciak** [comment]
I just use scroller in an area of circle Live preview
If scroller used over live preview widget it scrolls images + scrolls up/down
If scroller used outside of coverflow it scrolls up/down
See below video for details
[scroller.zip](https://github.com/Samsung/TAU-Design-Editor/files/3874430/scroller.zip)

**Comment by DohyungLim** [comment]
@lslachciak 
The tau 1.1.10 release is complete.
Does the issue reproduce on code.tizen.org?
I changed the tau of my project to 1.1.10.
But the scrolling problem does not occur.

Please email me a reproduced project so that I can test it.
Or send me a test demo link.

**Comment by lslachciak** [comment]
We are updating code.tizen.org now, as soon as we are done, we will share with you test demo link

**Comment by DohyungLim** [comment]
ok. thanks.

**Comment by lslachciak** [comment]
Dear @DohyungLim please find link to sample below:
https://code.tizen.org/demos?path=1.1%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Finteractive%2Fcoverflow%2Findex.html

The interesting thing is that the issue occurs only on the Linux machine
On Windows machine I can't observe this issue too

**Comment by lslachciak** [comment]
When disable 
`padding-bottom: 6.25rem`
in Developers tools, issue no longer occurs

**Comment by DohyungLim** [comment]
very good.
will you update the patch?

**Comment by lslachciak** [comment]
I'll take care of this issue.
Need to check few things

**Comment by DohyungLim** [comment]
okay.
If there is no problem after checking, please close the issue.

thanks.

**Comment by lslachciak** [comment]
issue fixed, we need to release TAU 1.1 and re-upload example to AWS

**Comment by lslachciak** [comment]
coverflow issue is fixed on code.tizen.org, closing this item
