### ISSUE TITLE
[mobile] [code.tizen.org] Missing image after clicking add button

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#445]
## Steps to reproduce
1. Open   https://docs.stg.tizen.org/staging/938/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_SectionChanger.htm
2. Click "use example"
3. Click live preview icon
4. Click add button
## Expected behaviour
new image is visible or some window with quesiton about locaiotn
## Actual behaviour
missing image
![image](https://user-images.githubusercontent.com/2246331/69815326-55f57c80-11f6-11ea-809b-2639c30527af.png)
add button stays focused

**Comment by singa2000** [comment]
I  think we  need  to fix.

**Comment by lslachciak** [comment]
PR merged
waiting for code.tizen.org update

**Comment by lslachciak** [comment]
work well on https://docs.stg.tizen.org/staging/959/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_SectionChanger.htm
