### ISSUE TITLE
[mobile] [code.tizen.org] Text input - X mark is not deleting text

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#446]
## Steps to reproduce
1. Visit https://docs.stg.tizen.org/staging/938/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_TextInput.htm
2. Click "use example"
3. Click Live preview icon
4. Enter some text in any text field
5. CLick X cross
## Expected behaviour
Text field is cleared
## Actual behaviour
Text field is not cleared
![image](https://user-images.githubusercontent.com/2246331/69816045-e54f5f80-11f7-11ea-8c73-9444b7ccb96a.png)

**Comment by lslachciak** [comment]
This issue seems similar to https://github.com/Samsung/TAU-Design-Editor/issues/444

**Comment by singa2000** [comment]
I think we  need to  fix.
TAU 1.0 is  good  working.

**Comment by lslachciak** [comment]
good working locally now

**Comment by lslachciak** [comment]
works well on https://docs.stg.tizen.org/staging/959/application/web/api/5.5/ui_fw_api/Mobile_UIComponents/mobile_TextInput.htm
