### ISSUE TITLE
[mobile] [wearable] code.tizen.org No wearable slider example

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#447]
Visit https://docs.tizen.org/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_slider.htm
## Expected behaviour
Use example button
## Actual behaviour
No Use example button

**Comment by singa2000** [comment]
Tizen 5.0 Wearable has the Slider example button.
So Tizen 5.5 is also needed.

**Comment by lslachciak** [comment]
I can't find "use example" button on
https://docs.tizen.org/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_slider.htm
Looks like we need to modify both 5.0 and 5.5 docs

**Comment by singa2000** [comment]
I see the "use example" button in the follonwgs link.
https://developer.tizen.org/development/api-references/web-application?redirect=https://developer.tizen.org/dev-guide/5.0.0/org.tizen.web.apireference/html/ui_fw_api/Wearable_UIComponents/wearable_slider.htm

**Comment by lslachciak** [comment]
@singa2000 you are right,
I prepared PR https://github.com/Samsung/tizen-docs/pull/959
and updated sample TC

**Comment by lslachciak** [comment]
Sample linke:
https://docs.stg.tizen.org/staging/959/application/web/api/5.5/ui_fw_api/Wearable_UIComponents/wearable_slider.htm

**Comment by lslachciak** [comment]
Waiting for final approval by tester
