### ISSUE TITLE
After trying add image, there is no image content

### ISSUE THREAD

**Issue by korneliakobiela** [Samsung/TAU-Design-Editor#59]
[Test version]

- 0509 latest commit

[How to reproduce]

- WAPPL -> Create Wizard Project -> Template ->  Wearable -> Version 4.0 -> TAU Basic

- index.html -> launch the Desgin Editor

- Drag&drop the image widget  -> select the image file

[Problem]

I can't see the image

**Comment by lslachciak** [comment]
@korneliakobiela is this issue resolved? if yes, please close it
