### ISSUE TITLE
ToggleSlider has wrong look in wearable profile

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU-Design-Editor#79]
Wrong:
![image](https://user-images.githubusercontent.com/29534410/59415317-8752cb00-8dc3-11e9-9bff-26ed5e56909d.png)

Correct:
![image](https://user-images.githubusercontent.com/29534410/59415347-95a0e700-8dc3-11e9-8b14-42bcbe605dab.png)

**Comment by lslachciak** [comment]
@TomaszLukawskiSam PR merged, can we close this issue?
